
apiVersion: v1
kind: ReplicationController
metadata:
  name: springbootapprc
spec:
  replicas: 2
  #strategy:
    #type: Recreate
  #selector:
    #matchLabels:
      #app: springbootapp
  template:
    metadata:
      name: springbootapppod
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootappcontainer
        image: phanidocker1912/spring-boot-mongo-docker:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name:  MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
          # resources:
          #requests:
          #cpu: 200m
          #memory: 256Mi
          #limits:
          #cpu: 1
          #memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: springbootappsvc
spec:
  type: NodePort
  selector:
    app: springbootapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
spec:
  type:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
